version: '3.4'
services:
  passbolt:
    image: passbolt/passbolt:2.11.0-debian
    tty: true
    depends_on:
      - db
    env_file:
      - env/passbolt.env
    volumes:
      - gpg_volume:/var/www/passbolt/config/gpg
      - images_volume:/var/www/passbolt/webroot/img/public
      - ssl_volume:/etc/ssl/certs
    tmpfs:
      - /run
    command: ["/usr/bin/wait-for.sh", "db:3306", "--", "/docker-entrypoint.sh"]
    ports:
      - 80:80
      - 443:443

volumes:
  gpg_volume:
  images_volume:
  ssl_volume:
